name: Lighthouse
on:
  schedule:
  - cron:  '0 6 * * *' # 06:00 UTC
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    getpsresults:
      env:
        URLS: https://nomes.info,https://nomes.info/nomes-populares,https://nomes.info/top-temas,https://nomes.info/pedros,https://nomes.info/unisexo/i,https://nomes.info/maria
        PSURL: https://pagespeed-insights-svg.openode.dev
        PSRDESKTOP: psi-audit-desktop
        PSRMOBILE: psi-audit-mobile
        RESULTSFOLDER: documentation/reports
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Create local changes
        run: | # Have to be sure a folder is present if not, make it
            mkdir -p ${RESULTSFOLDER}
            IFS=',' read -r -a HOSTS <<< $URLS
            for i in "${!HOSTS[@]}"; do
              position=$(( $i + 1 ))
              while [ ! "$auditDesktop" ]; do
                auditDesktop=$(curl "${PSURL}/?url=${HOSTS[$i]}&theme=dark&categories=30&tests=3")
              done
              cat <<< "$auditDesktop" > ./${RESULTSFOLDER}/${PSRDESKTOP}-${position}.svg
              while [ ! "$auditMobile" ]; do
                auditMobile=$(curl "${PSURL}/?url=${HOSTS[$i]}&strategy=mobile&theme=dark&categories=30&tests=3")
              done
              cat <<< "$auditMobile" > ./${RESULTSFOLDER}/${PSRMOBILE}-${position}.svg
              unset auditDesktop
              unset auditMobile
            done
      - name: Commit files 
        run: |
          git add .
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions[bot]"
          git diff --quiet && git diff --staged --quiet || git commit -am "🔁 CI" -m "Updated PageSpeed Insights results SVGs"
      - name: Push changes
        uses: ad-m/github-push-action@master # This is a premade github action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
